export const CALC_ACTION_TYPES = {
    SET_CALC_ADD_NUM_TO_DISPLAY_RESULT: 'calc/SET_CALC_ADD_NUM_TO_DISPLAY_RESULT',
    SET_CALC_NEW_CALCULATION:'calc/SET_CALC_NEW_CALCULATION',
    SET_CALC_RESET_FORMULA_AND_RESULTS:'calc/SET_CALC_RESET_FORMULA_AND_RESULTS',
    SET_CALC_BACKSPACE:'calc/SET_CALC_BACKSPACE',
}